name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # (Opcional) Instalar Chrome caso seus testes precisem de navegador
      # - name: Setup Chrome
      #   uses: browser-actions/setup-chrome@v1

      - name: Build & Test
        run: mvn -B clean test

      - name: Upload Surefire reports (sempre)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/surefire-reports/*'
